# Generated by Django 3.1.2 on 2020-10-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=500, verbose_name='')),
                ('input_string', models.CharField(max_length=500, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='selectedRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=500, verbose_name='')),
                ('api_id', models.CharField(max_length=100, verbose_name='')),
                ('title', models.CharField(default='recipe', max_length=500, verbose_name='')),
                ('image', models.CharField(default='image', max_length=500, verbose_name='')),
                ('usedIngredients', models.CharField(default='ingredients', max_length=10000, verbose_name='')),
                ('missedIngredients', models.CharField(default='ingredients', max_length=10000, verbose_name='')),
            ],
        ),
    ]
